from rdkit import Chem
from rdkit.Chem import AllChem

def smiles_to_xyz(smiles, filename):
    
    mol = Chem.MolFromSmiles(smiles) # Convert SMILES to RDKit molecule object
    mol = Chem.AddHs(mol)  # Add hydrogens to the molecule

    # Generate 3D coordinates

    AllChem.EmbedMolecule(mol)
    AllChem.UFFOptimizeMolecule(mol)

    # Extract atom positions and write to XYZ format

    with open(filename, 'w') as f:
        num_atoms = mol.GetNumAtoms()
        f.write(f"{num_atoms}\n")
        f.write(f"Generated by RDKit from SMILES: {smiles}\n")

        for atom in mol.GetAtoms():
            pos = mol.GetConformer().GetAtomPosition(atom.GetIdx())
            element = atom.GetSymbol()
            f.write(f"{element} {pos.x:.4f} {pos.y:.4f} {pos.z:.4f}\n")

# Example usage
            
smiles = "CC(O)=O"
filename = "acetic.xyz"
smiles_to_xyz(smiles, filename)